import path from 'node:path';
import type { Order, ShopRepositories } from '@jubilant-adventure/shop-domain';
import { createBaselineSeed, fixtureIds } from '@jubilant-adventure/test-data';
import { Verifier } from '@pact-foundation/pact';
import { createApp, createRuntime } from '../../apps/api/src/app';
import { createAccessToken } from '../../apps/api/src/auth/token';
import { createServer } from '../../apps/api/src/server';

const orderId = '00000000-0000-4000-8000-000000000701';

describe('Hono provider Pact verification', () => {
    test('verifies the pacts generated by the consumer suite', async () => {
        const runtime = createRuntime({
            mode: 'test',
            tokenSecret: 'pact-provider-secret',
        });
        const app = createApp({
            repositories: runtime.repositories as ShopRepositories,
            clock: runtime.clock,
            idGenerator: runtime.idGenerator,
            mode: 'test',
            tokenSecret: 'pact-provider-secret',
            testControlKey: 'pact-control',
        });
        const server = createServer(0, app);
        await new Promise<void>((resolve, reject) => {
            server.once('error', reject);
            server.listen(0, resolve);
        });
        const address = server.address();
        if (!address || typeof address === 'string')
            throw new Error('Pact provider did not expose a TCP address');
        const token = createAccessToken(
            { userId: fixtureIds.user, role: 'user' },
            'pact-provider-secret',
            runtime.clock.now(),
        );
        const adminToken = createAccessToken(
            { userId: fixtureIds.admin, role: 'admin' },
            'pact-provider-secret',
            runtime.clock.now(),
        );
        const pactUrls = [
            path.resolve(
                process.cwd(),
                'pacts/ReactShopClient-HonoShopApi.json',
            ),
        ];
        const requestFilter = (
            request: { headers: Record<string, string | string[] | undefined> },
            _response: unknown,
            next: () => void,
        ): void => {
            if (request.headers.authorization === 'Bearer pact-test-token')
                request.headers.authorization = `Bearer ${token}`;
            if (
                request.headers.authorization === 'Bearer pact-admin-test-token'
            )
                request.headers.authorization = `Bearer ${adminToken}`;
            next();
        };
        try {
            await new Verifier({
                providerBaseUrl: `http://127.0.0.1:${address.port}`,
                pactUrls,
                logLevel: 'warn',
                stateHandlers: {
                    'baseline users exist': async () => {
                        runtime.reset(createBaselineSeed());
                    },
                    'active products exist': async () => {
                        runtime.reset(createBaselineSeed());
                    },
                    'a user has a non-empty cart': async () => {
                        runtime.reset(createBaselineSeed());
                        runtime.services.carts.setItem(
                            fixtureIds.user,
                            fixtureIds.mug,
                            1,
                        );
                    },
                    'a user has an empty cart': async () => {
                        runtime.reset(createBaselineSeed());
                    },
                    'a pending order exists': async () => {
                        runtime.reset(createBaselineSeed());
                        const order: Order = {
                            id: orderId,
                            userId: fixtureIds.user,
                            idempotencyKey: 'seed-order',
                            items: [
                                {
                                    productId: fixtureIds.mug,
                                    name: 'Comet Mug',
                                    unitPrice: {
                                        amount: 1299,
                                        currency: 'USD',
                                    },
                                    quantity: 1,
                                    total: { amount: 1299, currency: 'USD' },
                                },
                            ],
                            total: { amount: 1299, currency: 'USD' },
                            status: 'pending',
                            createdAt: '2026-01-01T00:00:00.000Z',
                            updatedAt: '2026-01-01T00:00:00.000Z',
                        };
                        runtime.repositories.orders.save(order);
                    },
                },
                requestFilter,
            }).verifyProvider();
        } finally {
            await new Promise<void>((resolve, reject) =>
                server.close((error) => (error ? reject(error) : resolve())),
            );
        }
    });
});
