// This file is generated by scripts/generate-api-client.mjs. Do not edit it directly.
export interface ApiClientOptions {
    baseUrl?: string;
    token?: string;
    fetchImplementation?: typeof globalThis.fetch;
}

export interface ApiClient {
    request(path: string, init?: RequestInit): Promise<Response>;
}

export const createApiClient = ({
    baseUrl = '',
    token,
    fetchImplementation = globalThis.fetch,
}: ApiClientOptions = {}): ApiClient => ({
    request: (path, init = {}) => {
        const headers = new Headers(init.headers);
        headers.set('accept', 'application/json');
        if (token) headers.set('authorization', `Bearer ${token}`);
        return fetchImplementation(`${baseUrl}${path}`, { ...init, headers });
    },
});
