// This file is generated by scripts/generate-api-client.mjs. Do not edit it directly.
export interface components {
    schemas: {
        LoginResponse: {
            token: string;
            expiresIn: number;
            user: components['schemas']['User'];
        };
        User: {
            id: string;
            email: string;
            role: 'user' | 'admin';
        };
        Error: {
            code: string;
            message: string;
            fields?: {
                [key: string]: string;
            };
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        ProductList: {
            items: Array<components['schemas']['Product']>;
            total: number;
            page: number;
            pageSize: number;
            totalPages: number;
        };
        Product: {
            id: string;
            name: string;
            description: string;
            category: string;
            price: {
                amount: number;
                currency: string;
            };
            stock: number;
            active: boolean;
        };
        Cart: {
            userId: string;
            items: Array<{
                productId: string;
                quantity: number;
            }>;
        };
        CartItemRequest: {
            productId: string;
            quantity: number;
        };
        CheckoutResponse: {
            order: components['schemas']['Order'];
            replayed: boolean;
        };
        Order: {
            id: string;
            userId: string;
            idempotencyKey: string;
            items: Array<{
                productId: string;
                name: string;
                unitPrice: {
                    amount: number;
                    currency: string;
                };
                quantity: number;
                total: {
                    amount: number;
                    currency: string;
                };
            }>;
            total: {
                amount: number;
                currency: string;
            };
            status: 'pending' | 'paid' | 'processing' | 'shipped' | 'cancelled';
            createdAt: string;
            updatedAt: string;
        };
        OrderStatusRequest: {
            status: 'pending' | 'paid' | 'processing' | 'shipped' | 'cancelled';
        };
    };
}

export interface paths {
    '/auth/login': {
        post: {
            requestBody: {
                content: {
                    'application/json': components['schemas']['LoginRequest'];
                };
            };
            responses: {
                '200': {
                    content: {
                        'application/json': components['schemas']['LoginResponse'];
                    };
                };
                '400': {
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
                '401': {
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
            };
        };
    };
    '/products': {
        get: {
            query: {
                page?: number;
                pageSize?: number;
                search?: string;
                category?: string;
                sort?: 'name' | 'price' | 'stock';
                direction?: 'asc' | 'desc';
            };
            responses: {
                '200': {
                    content: {
                        'application/json': components['schemas']['ProductList'];
                    };
                };
                '400': {
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
            };
        };
    };
    '/products/{id}': {
        get: {
            path: {
                id: string;
            };
            responses: {
                '200': {
                    content: {
                        'application/json': components['schemas']['Product'];
                    };
                };
                '400': {
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
                '404': {
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
            };
        };
    };
    '/cart/items': {
        post: {
            requestBody: {
                content: {
                    'application/json': components['schemas']['CartItemRequest'];
                };
            };
            responses: {
                '200': {
                    content: {
                        'application/json': components['schemas']['Cart'];
                    };
                };
                '400': {
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
                '401': {
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
                '404': {
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
                '409': {
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
            };
        };
    };
    '/orders': {
        post: {
            header: {
                'idempotency-key': string;
            };
            responses: {
                '200': {
                    content: {
                        'application/json': components['schemas']['CheckoutResponse'];
                    };
                };
                '201': {
                    content: {
                        'application/json': components['schemas']['CheckoutResponse'];
                    };
                };
                '400': {
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
                '401': {
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
                '409': {
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
            };
        };
    };
    '/orders/{id}': {
        get: {
            path: {
                id: string;
            };
            responses: {
                '200': {
                    content: {
                        'application/json': components['schemas']['Order'];
                    };
                };
                '400': {
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
                '401': {
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
                '403': {
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
                '404': {
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
            };
        };
    };
    '/orders/{id}/status': {
        patch: {
            path: {
                id: string;
            };
            requestBody: {
                content: {
                    'application/json': components['schemas']['OrderStatusRequest'];
                };
            };
            responses: {
                '200': {
                    content: {
                        'application/json': components['schemas']['Order'];
                    };
                };
                '400': {
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
                '401': {
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
                '403': {
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
                '404': {
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
                '409': {
                    content: {
                        'application/json': components['schemas']['Error'];
                    };
                };
            };
        };
    };
}
