name: Auto-merge Dependabot PRs

permissions:
    contents: read
    pull-requests: write
    issues: write

on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches: [latest]

jobs:
    auto-merge:
        runs-on: ubuntu-latest
        if: github.actor == 'dependabot[bot]'

        steps:
            - name: Wait for status checks
              uses: fountainhead/action-wait-for-check@v1.1.0
              id: wait-for-checks
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  checkName: 'test,security'
                  ref: ${{ github.event.pull_request.head.sha }}
                  timeoutSeconds: 600
                  intervalSeconds: 10

            - name: Check if all required checks passed
              if: steps.wait-for-checks.outputs.conclusion == 'success'
              run: echo "All checks passed, proceeding with auto-merge"

            - name: Enable auto-merge for Dependabot PRs
              if: steps.wait-for-checks.outputs.conclusion == 'success'
              run: |
                  gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Add comment on failure
              if: steps.wait-for-checks.outputs.conclusion == 'failure'
              uses: actions/github-script@v6
              with:
                  script: |
                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: '❌ Auto-merge failed because some checks did not pass. Please review manually.'
                      });

            - name: Add success comment
              if: steps.wait-for-checks.outputs.conclusion == 'success'
              uses: actions/github-script@v6
              with:
                  script: |
                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: '✅ All checks passed! Auto-merging this Dependabot PR.'
                      });
