name: Testomatio Tests

on:
  workflow_dispatch:
    inputs:
      grep:
        description: 'tests to grep '
        required: false
        default: ''
      run:
        description: 'Run flags'
        required: false
      testomatio:
        description: 'Testomatio key'
        required: true
jobs:
  generate_test_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: yarn
      - name: Generate test report
        run: yarn test -t "${{ github.event.inputs.grep }}"
        env:
          TESTOMATIO: "${{ github.event.inputs.testomatio }}"
          TESTOMATIO_RUN: "${{ github.event.inputs.run }}"
